name: cmiyc-dev
channels:
  - defaults
dependencies:
  - python=3.7.2
  - pip:
    - keras==2.2.4
    - matplotlib==3.0.3
    - numpy==1.16.2
    - pillow==5.4.1
    - scipy==1.2.1
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - pandas==0.24.2